---
title: "Stationary Distribution"
author: "Chetana"
date: "17/09/2022"
output: html_document
---

```{r}
library(expm)
p=matrix(c(0.3,0.7,0.7,0.3),ncol=2,byrow=T);p
p_100=p%^%100;p_100

```
```{r}
p=matrix(c(0.3,0.7,0.7,0.3),ncol=2,byrow = T)
k=nrow(p)
A=rbind(diag(k)-t(p),rep(1,k))
b=matrix(c(rep(0,k),1),ncol=1)
solve(t(A)%*%A,t(A)%*%b)

```

```{r}

p=matrix(c(0.5,0.25,0.25,0,0,0.25,0.25,0.5,0.25,0.5,0.25,0,0.25,0.25,0.25,0.25),ncol=4,byrow = T)
k=nrow(p)
A=rbind(diag(k)-t(p),rep(1,k))
b=matrix(c(rep(0,k),1),ncol=1)

solution=solve(t(A)%*%A,t(A)%*%b)
library(expm)
cat("limmiting Distribution",(p%^%100)[1,],"\nStationary Distribution",solution)
```
```{r}
p=matrix(c(0,0,0,0,1,1,0,0,0,0,1/2,1/2,0,0,0,1/3,1/3,1/3,0,0,1/4,1/4,1/4,1/4,0),ncol = 5,byrow = T);p
k=nrow(p)
A=rbind(diag(k)-t(p),rep(1,k))
b=matrix(c(rep(0,k),1),ncol=1)
library(expm)
solution=solve(t(A)%*%A,t(A)%*%b)
cat("limmiting Distribution",(p%^%100)[1,],"\nStationary Distribution",solution)

```

